pipeline { 
    environment { 
        registry = "lucasmocerinomonteiro/go-test-app" 
        registryCredential = 'id_docker_hub' 
        dockerImage = '' 
    }
    agent any 
    stages { 
        stage('Building our image') { 
            steps { 
                script { 
                    dockerImage = docker.build registry + ":$BUILD_NUMBER" 
                }
            } 
        }
        stage('Deploy our image') { 
            steps { 
                script { 
                docker.withRegistry( '', registryCredential ) { 
                        dockerImage.push() 
                    }
                } 
            }
        } 
        stage('Cleaning up') { 
            steps { 
                sh "docker rmi $registry:$BUILD_NUMBER" 
            }
        }
        stage('Docker deploy') { 
            steps { 
                ansiblePlaybook credentialsId: 'ec2-dev-web', disableHostKeyChecking: true, extras: "-e DOCKER_TAG=${BUILD_NUMBER}", installation: 'ansible', inventory: '.ansible/dev.inv', playbook: '.ansible/deploy-playbook.yml'
            }
        } 
    }
}